-- CreateTable
CREATE TABLE `pin` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `src` MEDIUMTEXT NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `url` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `image_width` INTEGER UNSIGNED DEFAULT 0,
    `image_height` INTEGER UNSIGNED DEFAULT 0,
    `pin_id` INTEGER NOT NULL,
    `unique_id` VARCHAR(32) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
